# Site settings
title: JRR Personal Blog
description: A personal blog with gratitude diary and daily journal
author: JRR
email: your-email@example.com

# Build settings
markdown: kramdown
theme: minima

# Collections
collections:
  gratitude:
    output: true
    permalink: /gratitude/:year/:month/:day/:title/
  journal:
    output: true
    permalink: /journal/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "gratitude"
    values:
      layout: "gratitude"
  - scope:
      path: ""
      type: "journal"
    values:
      layout: "journal"

# Exclude from build
exclude:
  - README.md
  - LICENSE
